package com.program.bookie.models;

public enum RequestType {
    LOGIN,
    REGISTER,
    GET_TOP_BOOKS,
    GET_BOOK_DETAILS,
    SEARCH_BOOK,
    GET_READING_STATUS,
    UPDATE_READING_STATUS,
    GET_USER_RATING,
    GET_IMAGE,
    GET_USER_REVIEW,
    SAVE_USER_REVIEW,
    GET_RANDOM_QUOTE,
    GET_USER_STATISTICS,
    GET_READING_INSIGHTS,
    GET_BOOK_REVIEWS,
    GET_REVIEW_COMMENTS,
    ADD_COMMENT,
    GET_NOTIFICATIONS,
    GET_NOTIFICATION_COUNT,
    MARK_NOTIFICATIONS_READ,
    CLEAR_NOTIFICATIONS,
    GET_BOOK_BY_ID,
    DISCONNECT

};