package com.program.bookie.models;

public enum RequestType {
    LOGIN,
    REGISTER,
    GET_TOP_BOOKS,
    GET_BOOK_DETAILS,
    SEARCH_BOOK,
    GET_READING_STATUS,
    UPDATE_READING_STATUS,
    GET_USER_RATING,
    GET_USER_REVIEW,
    SAVE_USER_REVIEW,
    GET_RANDOM_QUOTE,
    GET_USER_STATISTICS,
    GET_READING_INSIGHTS,
    DISCONNECT

};