package com.program.bookie.models;

public enum RequestType {
    LOGIN,
    REGISTER,
    GET_TOP_BOOKS,
    GET_BOOK_DETAILS,
    SEARCH_BOOK,
    GET_READING_STATUS,
    UPDATE_READING_STATUS,
    GET_USER_RATING,
    GET_IMAGE,
    GET_USER_REVIEW,
    SAVE_USER_REVIEW,
    GET_RANDOM_QUOTE,
    GET_USER_STATISTICS,
    GET_READING_INSIGHTS,
    GET_BOOK_REVIEWS,
    GET_REVIEW_COMMENTS,
    ADD_COMMENT,
    GET_USER_BOOKS_BY_STATUS,
    GET_BOOK_PROGRESS,
    UPDATE_BOOK_PROGRESS,
    DISCONNECT

};